defaultUser: guest
app:
  image: vprocontainers/vprofileapp
  tag: latest
  replicas: 1
  containerPort: 8080
  servicePort: 8080
db:
  image: vprocontainers/vprofiledb
  tag: latest
  replicas: 1
  containerPort: 3306
  servicePort: 3306
  storageClass: gp2
  storageSize: 3Gi
memcached:
  image: memcached
  tag: latest
  replicas: 1
  containerPort: 11211
  servicePort: 11211
rabbitmq:
  image: rabbitmq
  tag: latest
  replicas: 1
  containerPort: 5672
  servicePort: 5672
initcontainers:
  image: busybox
  command:
    - sh
    - -c
ingress:
  enabled: true
  host: vprofile.example.com
  servicePort: 8080
secrets:
  dbPassword: vprodbpass
  rmqPassword: guest
dockerregistry:
  enabled: false
  server: ""
  username: ""
  password: ""
  email: ""
